[2021-07-14 18:46:27 +0000] [2686] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:46:27 +0000] [2686] [INFO] Listening at: unix:myproject.sock (2686)
[2021-07-14 18:46:27 +0000] [2686] [INFO] Using worker: sync
[2021-07-14 18:46:27 +0000] [2689] [INFO] Booting worker with pid: 2689
[2021-07-14 18:46:27 +0000] [2689] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:27 +0000] [2689] [INFO] Worker exiting (pid: 2689)
[2021-07-14 18:46:27 +0000] [2690] [INFO] Booting worker with pid: 2690
[2021-07-14 18:46:27 +0000] [2690] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:27 +0000] [2690] [INFO] Worker exiting (pid: 2690)
[2021-07-14 18:46:27 +0000] [2686] [WARNING] Worker with pid 2690 was terminated due to signal 15
[2021-07-14 18:46:27 +0000] [2691] [INFO] Booting worker with pid: 2691
[2021-07-14 18:46:27 +0000] [2691] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:27 +0000] [2691] [INFO] Worker exiting (pid: 2691)
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loser/Database/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2021-07-14 18:46:28 +0000] [2692] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:46:28 +0000] [2692] [INFO] Listening at: unix:myproject.sock (2692)
[2021-07-14 18:46:28 +0000] [2692] [INFO] Using worker: sync
[2021-07-14 18:46:28 +0000] [2695] [INFO] Booting worker with pid: 2695
[2021-07-14 18:46:28 +0000] [2695] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:28 +0000] [2695] [INFO] Worker exiting (pid: 2695)
[2021-07-14 18:46:28 +0000] [2696] [INFO] Booting worker with pid: 2696
[2021-07-14 18:46:28 +0000] [2696] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:28 +0000] [2696] [INFO] Worker exiting (pid: 2696)
[2021-07-14 18:46:28 +0000] [2692] [WARNING] Worker with pid 2696 was terminated due to signal 15
[2021-07-14 18:46:28 +0000] [2692] [INFO] Shutting down: Master
[2021-07-14 18:46:28 +0000] [2692] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:46:31 +0000] [2697] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:46:31 +0000] [2697] [INFO] Listening at: unix:myproject.sock (2697)
[2021-07-14 18:46:31 +0000] [2697] [INFO] Using worker: sync
[2021-07-14 18:46:31 +0000] [2700] [INFO] Booting worker with pid: 2700
[2021-07-14 18:46:31 +0000] [2700] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:31 +0000] [2701] [INFO] Booting worker with pid: 2701
[2021-07-14 18:46:31 +0000] [2700] [INFO] Worker exiting (pid: 2700)
[2021-07-14 18:46:31 +0000] [2701] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:31 +0000] [2701] [INFO] Worker exiting (pid: 2701)
[2021-07-14 18:46:31 +0000] [2697] [WARNING] Worker with pid 2701 was terminated due to signal 15
[2021-07-14 18:46:31 +0000] [2697] [INFO] Shutting down: Master
[2021-07-14 18:46:31 +0000] [2697] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:46:34 +0000] [2702] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:46:34 +0000] [2702] [INFO] Listening at: unix:myproject.sock (2702)
[2021-07-14 18:46:34 +0000] [2702] [INFO] Using worker: sync
[2021-07-14 18:46:34 +0000] [2705] [INFO] Booting worker with pid: 2705
[2021-07-14 18:46:34 +0000] [2705] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:34 +0000] [2705] [INFO] Worker exiting (pid: 2705)
[2021-07-14 18:46:34 +0000] [2706] [INFO] Booting worker with pid: 2706
[2021-07-14 18:46:34 +0000] [2706] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cfehome'
[2021-07-14 18:46:34 +0000] [2706] [INFO] Worker exiting (pid: 2706)
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loser/Database/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2021-07-14 18:51:14 +0000] [2805] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:51:14 +0000] [2805] [INFO] Listening at: unix:myproject.sock (2805)
[2021-07-14 18:51:14 +0000] [2805] [INFO] Using worker: sync
[2021-07-14 18:51:14 +0000] [2808] [INFO] Booting worker with pid: 2808
[2021-07-14 18:51:14 +0000] [2808] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:14 +0000] [2808] [INFO] Worker exiting (pid: 2808)
[2021-07-14 18:51:14 +0000] [2805] [INFO] Shutting down: Master
[2021-07-14 18:51:14 +0000] [2805] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:51:16 +0000] [2809] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:51:16 +0000] [2809] [INFO] Listening at: unix:myproject.sock (2809)
[2021-07-14 18:51:16 +0000] [2809] [INFO] Using worker: sync
[2021-07-14 18:51:16 +0000] [2812] [INFO] Booting worker with pid: 2812
[2021-07-14 18:51:16 +0000] [2812] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:16 +0000] [2813] [INFO] Booting worker with pid: 2813
[2021-07-14 18:51:16 +0000] [2812] [INFO] Worker exiting (pid: 2812)
[2021-07-14 18:51:16 +0000] [2813] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:16 +0000] [2813] [INFO] Worker exiting (pid: 2813)
[2021-07-14 18:51:16 +0000] [2814] [INFO] Booting worker with pid: 2814
[2021-07-14 18:51:16 +0000] [2814] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:16 +0000] [2814] [INFO] Worker exiting (pid: 2814)
[2021-07-14 18:51:16 +0000] [2809] [WARNING] Worker with pid 2814 was terminated due to signal 15
[2021-07-14 18:51:16 +0000] [2809] [WARNING] Worker with pid 2813 was terminated due to signal 15
[2021-07-14 18:51:16 +0000] [2809] [INFO] Shutting down: Master
[2021-07-14 18:51:16 +0000] [2809] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:51:18 +0000] [2815] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:51:18 +0000] [2815] [INFO] Listening at: unix:myproject.sock (2815)
[2021-07-14 18:51:18 +0000] [2815] [INFO] Using worker: sync
[2021-07-14 18:51:18 +0000] [2818] [INFO] Booting worker with pid: 2818
[2021-07-14 18:51:18 +0000] [2818] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:18 +0000] [2818] [INFO] Worker exiting (pid: 2818)
[2021-07-14 18:51:18 +0000] [2815] [INFO] Shutting down: Master
[2021-07-14 18:51:18 +0000] [2815] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:51:22 +0000] [2822] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:51:22 +0000] [2822] [INFO] Listening at: unix:myproject.sock (2822)
[2021-07-14 18:51:22 +0000] [2822] [INFO] Using worker: sync
[2021-07-14 18:51:22 +0000] [2825] [INFO] Booting worker with pid: 2825
[2021-07-14 18:51:22 +0000] [2825] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/loser/barrelwisdom/Database/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Databae'
[2021-07-14 18:51:22 +0000] [2825] [INFO] Worker exiting (pid: 2825)
[2021-07-14 18:51:22 +0000] [2822] [INFO] Shutting down: Master
[2021-07-14 18:51:22 +0000] [2822] [INFO] Reason: Worker failed to boot.
[2021-07-14 18:52:24 +0000] [2841] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:52:24 +0000] [2841] [INFO] Listening at: unix:myproject.sock (2841)
[2021-07-14 18:52:24 +0000] [2841] [INFO] Using worker: sync
[2021-07-14 18:52:24 +0000] [2844] [INFO] Booting worker with pid: 2844
[2021-07-14 18:52:24 +0000] [2845] [INFO] Booting worker with pid: 2845
[2021-07-14 18:52:25 +0000] [2846] [INFO] Booting worker with pid: 2846
[2021-07-14 18:59:16 +0000] [2841] [INFO] Handling signal: term
[2021-07-14 18:59:16 +0000] [2844] [INFO] Worker exiting (pid: 2844)
[2021-07-14 18:59:16 +0000] [2845] [INFO] Worker exiting (pid: 2845)
[2021-07-14 18:59:16 +0000] [2846] [INFO] Worker exiting (pid: 2846)
[2021-07-14 18:59:17 +0000] [2841] [INFO] Shutting down: Master
[2021-07-14 18:59:18 +0000] [2925] [INFO] Starting gunicorn 20.1.0
[2021-07-14 18:59:18 +0000] [2925] [INFO] Listening at: unix:myproject.sock (2925)
[2021-07-14 18:59:18 +0000] [2925] [INFO] Using worker: sync
[2021-07-14 18:59:18 +0000] [2928] [INFO] Booting worker with pid: 2928
[2021-07-14 18:59:18 +0000] [2929] [INFO] Booting worker with pid: 2929
[2021-07-14 18:59:18 +0000] [2930] [INFO] Booting worker with pid: 2930
[2021-07-14 19:02:13 +0000] [2925] [INFO] Handling signal: term
[2021-07-14 19:02:13 +0000] [2928] [INFO] Worker exiting (pid: 2928)
[2021-07-14 19:02:13 +0000] [2929] [INFO] Worker exiting (pid: 2929)
[2021-07-14 19:02:13 +0000] [2930] [INFO] Worker exiting (pid: 2930)
[2021-07-14 19:02:13 +0000] [2925] [INFO] Shutting down: Master
[2021-07-14 19:02:15 +0000] [2981] [INFO] Starting gunicorn 20.1.0
[2021-07-14 19:02:15 +0000] [2981] [INFO] Listening at: http://127.0.0.1:8000 (2981)
[2021-07-14 19:02:15 +0000] [2981] [INFO] Using worker: sync
[2021-07-14 19:02:15 +0000] [2984] [INFO] Booting worker with pid: 2984
[2021-07-14 19:02:15 +0000] [2985] [INFO] Booting worker with pid: 2985
[2021-07-14 19:02:15 +0000] [2986] [INFO] Booting worker with pid: 2986
[2021-07-14 19:02:35 +0000] [2981] [INFO] Handling signal: term
[2021-07-14 19:02:35 +0000] [2984] [INFO] Worker exiting (pid: 2984)
[2021-07-14 19:02:35 +0000] [2985] [INFO] Worker exiting (pid: 2985)
[2021-07-14 19:02:35 +0000] [2986] [INFO] Worker exiting (pid: 2986)
[2021-07-14 19:02:36 +0000] [2981] [INFO] Shutting down: Master
[2021-07-14 19:02:36 +0000] [2995] [INFO] Starting gunicorn 20.1.0
[2021-07-14 19:02:36 +0000] [2995] [INFO] Listening at: http://127.0.0.1:8000 (2995)
[2021-07-14 19:02:36 +0000] [2995] [INFO] Using worker: sync
[2021-07-14 19:02:36 +0000] [2998] [INFO] Booting worker with pid: 2998
[2021-07-14 19:02:36 +0000] [2999] [INFO] Booting worker with pid: 2999
[2021-07-14 19:02:36 +0000] [3000] [INFO] Booting worker with pid: 3000
[2021-07-14 19:03:13 +0000] [2995] [INFO] Handling signal: term
[2021-07-14 19:03:13 +0000] [2998] [INFO] Worker exiting (pid: 2998)
[2021-07-14 19:03:13 +0000] [2999] [INFO] Worker exiting (pid: 2999)
[2021-07-14 19:03:13 +0000] [3000] [INFO] Worker exiting (pid: 3000)
[2021-07-14 19:03:14 +0000] [2995] [INFO] Shutting down: Master
[2021-07-14 19:03:32 +0000] [814] [INFO] Starting gunicorn 20.1.0
[2021-07-14 19:03:32 +0000] [814] [INFO] Listening at: http://127.0.0.1:8000 (814)
[2021-07-14 19:03:32 +0000] [814] [INFO] Using worker: sync
[2021-07-14 19:03:32 +0000] [905] [INFO] Booting worker with pid: 905
[2021-07-14 19:03:32 +0000] [910] [INFO] Booting worker with pid: 910
[2021-07-14 19:03:32 +0000] [912] [INFO] Booting worker with pid: 912
